# Shopify store feed configuration
# IMPORTANT: Don't commit access tokens to git!
# Use environment variables: ${SHOPIFY_TOKEN_FR}
# Or set them as GitHub Secrets for Actions

stores:
  - name: FR
    shop_domain: bisgaardshoes.fr
    access_token: ${SHOPIFY_TOKEN_FR}
    language: fr
    currency: EUR
# Add more stores as needed
